print-status: False

api:
    server:
        scheme: http
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

swagger:
    schemes: [${api.server.scheme}]
    host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port}
