print-status: False

api:
    # server:
    #     exposed:
    #         static-host: ${SERVER_EXPOSED_STAIC_HOST:default}
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

swagger:
    schemes: [https]
    host: ${SWAGGER_HOST:localhost}
    port: "80"
