print-status: False
api:
    name: NetflixClone
    extension: yml
    dependency:
        update: False
        list:
            web: [Popen,Path]
            local: []
    list: [globals]
    language: EN-US
    git:
        url: https://github.com/viniciusrosner/
        extension: git

    server:
        scheme: http
        host: 0.0.0.0
        port: 7557
        base-url: /netflix


swagger:
    # schemes: [${api.server.scheme}] ###- comented due automation
    # host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- comented due automation
    info:
        title: ${api.name}
        description: Just cats
        version: 0.0.1
        terms-of-service: http://swagger.io/terms/
        contact:
            name: Vinicius Rosner
            email: viniciusrosner@gmail.com
        license:
            name: Apache 2.0 / MIT License
            url: http://www.apache.org/licenses/LICENSE-2.0.html

python:
    version: 3.9
